### ISSUE TITLE
Erro appears when placing an order without having funds

### ISSUE THREAD

**Issue by GuyFawkesII** [DarrenWestwood/greed#13]
I placed an order without having funds and then when I Click on "add funds" the bot just stops working 
[https://imgur.com/a/xrb09nQ](url)
and the bot to be restarted from terminal to work again .

**Comment by DarrenWestwood** [comment]
Hi @GuyFawkesII,

I will look into replicating this issue on my end. Thanks for reporting.

**Comment by DarrenWestwood** [comment]
Hi @GuyFawkesII ,

This error is caused by the `refill_on_checkout` setting being set to yes by default in the config file. This is an option that only works with Credit Cards.

Please set the `refill_on_checkout = no` in your config file.

**Comment by DarrenWestwood** [comment]
b1b1777 sets `refill_on_checkout = no` by default
