### ISSUE TITLE
Hosting problem

### ISSUE THREAD

**Issue by Milan-99** [DarrenWestwood/greed#21]
Hello
First of all , thanks for making this code public.
Can you please suggest a best hosting website where we can host the bot 24/7 . I tried in many website but couldn't figure out the callback url stuff in other hosting site.
It will be great if you write about hosting it on one of the hosting site.

**Comment by DarrenWestwood** [comment]
Hi @Milan-99 
Thank you for your interest in this project. Please could you try deploy using https://www.heroku.com/

* Login to heroku and push your bot to heroku master to launch it into production using the following commands:
```
git init .
git add .
git commit -m "Deploy to Heroku"
heroku login -i
heroku git:remote -a {your-heroku-project-name}
git push heroku master
```
* You can now start the greed bot and blockonomics callback from the Heroku Dashboard > Resources.
![](assets/images/heroku.png) 
* To set the HTTP Callback URL on the Blockonomics Merchants Page, combine the Heroku App URL with `/callback?secret=YOUR_SECRET`
	eg. https://greed.herokuapp.com/callback?secret=YOUR_SECRET

Please let me know if you have any further queries I can assist you with setting up.

**Comment by Milan-99** [comment]
I uploaded the file successfully to heroku but when I run the core.py file in  heroku console , its says edit the config file. Does that means I have to edit the file in heroku as well?

**Comment by DarrenWestwood** [comment]
You need to edit the config file and upload it to your server. Upload the edited file with the following commands:
```
git add config/config.ini
git commit -m "Upload config file"
git push heroku master
```
Also be sure to ensure the `is_template` flag has been set to `no` in the config file before uploading to your server.
