### ISSUE TITLE
Could not find matching xpub

### ISSUE THREAD

**Issue by limonsafayet** [DarrenWestwood/greed#24]
I have set the HTTP Callback URL on the Blockonomics Merchants Page which is deployed in HEROKU, everything is working fine. But when I am trying to Top up every time this error is happening. **Please help me**. 

![error](https://user-images.githubusercontent.com/23733953/108390677-1bcd2c00-723b-11eb-8a9f-aa8f7f3d37ed.PNG)

**Comment by DarrenWestwood** [comment]
Hi @LimonSafayet,

This does appear to be an issue in the code. The pull request to resolve the new address issue can be tracked [here](https://github.com/DarrenWestwood/greed/pull/25) and will be merged shortly.

Thank you for reporting this issue.

**Comment by DarrenWestwood** [comment]
Hi @LimonSafayet,

Please check your callback URL is correctly set on Blockonomics and the secret matches in the config.ini file, as a difference in these values would cause the issue reported.
