### ISSUE TITLE
Remove Test Code 

### ISSUE THREAD

**Issue by DarrenWestwood** [DarrenWestwood/greed#4]
The payment does not wait in the background but halts further bot execution indefinitely or till a payment message is received via websocket.

**Comment by shivaenigma** [comment]
We make websocket work exactly like production UI
 - It doesn't wait on send payment screen
 - Websocket will wait on server for 10 min and print message payment confirmed (on zero confirm) just like production

**Comment by DarrenWestwood** [comment]
Removed test code in https://github.com/DarrenWestwood/greed/pull/9
