### ISSUE TITLE
How to remove the location

### ISSUE THREAD

**Issue by B4DCUP1D** [DarrenWestwood/greed#42]
Location bugs the bot because people using my bot are not included in the criteria (France, VPN..) How can I delete the elements because removing the lines corresponding to the location the bot no longer works.

**Comment by DarrenWestwood** [comment]
Hi @B4DCUP1D,

Please let me know more about your desired behavior and the lines you are trying to remove. 

If you are trying to remove the French language from the bot, this can be achieved by editing the config file with your language choices and default accordingly:
https://github.com/DarrenWestwood/greed/blob/master/config/template_config.toml#L15-L17

Kind regards
