### ISSUE TITLE
Bitcoin

### ISSUE THREAD

**Issue by WHityop** [DarrenWestwood/greed#43]
Bitcoin is not showing in Payment options

**Comment by ndevmetax** [comment]
> Bitcoin is not showing in Payment options

I had a similar issue and i sorted it out via live chat with customer support https://direct.lc.chat/14390013/

**Comment by DarrenWestwood** [comment]
Hi @WHityop,

Please can you confirm you are using the latest files from this github repository: https://github.com/DarrenWestwood/greed?

To confirm your files are correct, the following lines of code should be present in the worker.py file, which add the Bitcoin option in the bot:
https://github.com/DarrenWestwood/greed/blob/master/worker.py#L764-L766

Kind regards
