### ISSUE TITLE
Use polling instead of callbacks to watch for new payments

### ISSUE THREAD

**Issue by DarrenWestwood** [DarrenWestwood/greed#47]
Using a polling system to watch for payments, removes the requirement for a public facing callback url. This simplifies the setup procedure, and matches greed bot, which polls telegram for new messages. This also has the added advantage of working on a local machine.
The Blockonomics searchhistory api endpoint can be used to check for new transactions: https://www.blockonomics.co/views/api.html#history

**Comment by blockonomics** [comment]
Lets think about design/implications for this. What about using our websocket API ?
