### ISSUE TITLE
Test bench doesn't work with polling

### ISSUE THREAD

**Issue by shivaenigma** [DarrenWestwood/greed#51]
Think about how to implement
Sanbox in Paypal

**Comment by shivaenigma** [comment]
#54  gave me an idea on what to do about this.

- We must switch to use api/get_logs instead of using searchhistory api call
- This way test bench will work 
- get_logs API call has to be internally changed to give only the desired store logs / any other changes to avoid giving out excessive data

**Comment by DarrenWestwood** [comment]
Closed in https://github.com/DarrenWestwood/greed/pull/60
