### ISSUE TITLE
Multiple Blockonomics Stores

### ISSUE THREAD

**Issue by DarrenWestwood** [DarrenWestwood/greed#54]
Multiple stores are currently hard to setup as a callback URL is required for this functionality. We should instead remove the secret and use the `match_account` parameter to choose the xpub to use:
https://www.blockonomics.co/views/api.html#newaddress

**Comment by shivaenigma** [comment]
It is good to use callback as then user can also see the latest payments in merchant dashboard. _match_account_ is depending on wallet xpub which may change and not reliable. There is a simple way for this:

Set secret in config like _mygreedbot912_
Use: https://www.blockonomics.co/api/test_callback?secret=mygreedbot912

This is ping callback that always returns 200, so it does nothing great. But good for pinging

**Comment by DarrenWestwood** [comment]
Updated README to include secret and callback: https://github.com/DarrenWestwood/greed
