### ISSUE TITLE
Callback problem

### ISSUE THREAD

**Issue by Domynyo** [DarrenWestwood/greed#6]
Hello I am following all tutorial i noticed you used heroku to generate the link I tried with ngrok but i am not able to make this work what should i pus as "secret" ?I am not able to make payments working

**Comment by DarrenWestwood** [comment]
Hi @Domynyo,

The secret can be anything of your choosing. You should ensure the same secret is entered into the Blockonomics Callback URL and the config.ini file.

Since you are deploying live to Heroku, you can set `use_websockets = False`.

Please let me know any further issues or suggestions.
