### ISSUE TITLE
Payment Functions not working 

### ISSUE THREAD

**Issue by okallo1233** [DarrenWestwood/greed#67]
Hi i really hope i can reach you to make this amazing bot work. 

I have followed the installation steps. 

I receive code 200 in my test log bench on the blockonomics platform. 

Everything seems to be working but i tried to send 4$ as real test payment. 
So i added funds via bitcoin and entered 4$ 
Then i sent from bitcoin wallet. 
The transaction appears in my blockonomics but the funds never appeared on the telegram account. 
Also i check the real payment transaction of 4$ never appear in "transaction list " function on the admin panel i can only see the credit transaction.

Also when i try the "Orders" function 
I get a error message from the bot i cant complete orders or refund them. 

Can you help me identify the problem for wich my transaction are not going inside the bot and orders functions not working 
Thank you very much. 

Here below i will give you picture to help you see the problem. 

![IMG_20230603_195123_855.jpg](https://github.com/DarrenWestwood/greed/assets/85691597/c55d42ac-e6e4-43cc-94b3-383e5ffa1563)

![IMG_20230603_195119_714.jpg](https://github.com/DarrenWestwood/greed/assets/85691597/6ed911be-59c9-4c77-958a-1d24afde0a58)

![IMG_20230603_195114_340.jpg](https://github.com/DarrenWestwood/greed/assets/85691597/cd8096fe-6baf-4438-9c9c-491d9f87b935)

![IMG_20230603_195103_706.jpg](https://github.com/DarrenWestwood/greed/assets/85691597/9e00b48b-989a-4c6c-a7e7-59549bbcfdb4)

![IMG_20230603_195059_988.jpg](https://github.com/DarrenWestwood/greed/assets/85691597/8d79acae-f1ca-4d72-a547-7e9f0e1ecc9b)

**Comment by DarrenWestwood** [comment]
Hi @okallo1233,

> Also when i try the "Orders" function
> I get a error message from the bot i cant complete orders or refund them.

This functionality is handled by the underlying greed bot, and is not affected by Blockonomics functionality. I have tested both the Complete order and refund functionality, and both are working correctly without issue on my end.

Looking at your screenshots, there appears to be an issue with one of the usernames, which may be causing all the issues.
`$CH$` does not seem to be a valid username, which would normally look like `@username`. If you have access to this account, please try updating the username without any special characters to verify this is causing the issues.

Let me know if this solves your problems.

Kind regards
