### ISSUE TITLE
Bot freezing after trying to add bitcoin funds

### ISSUE THREAD

**Issue by Domynyo** [DarrenWestwood/greed#7]
![bottg](https://user-images.githubusercontent.com/16639643/81515947-88271080-9336-11ea-9984-3ecc65639396.JPG)
Hello after I hit for example 10$ bitcoin in adding funds the bot freeze and stop working and need to get restarted by console I was able to push on heroku and launch with heroku run python core.py

Any idea on why this happening? thanks

**Comment by DarrenWestwood** [comment]
Hi @Domynyo,

- Please ensure you have entered a callback URL into the Blockonomics website? eg. http://localhost/callback?secret=YOUR_SECRET
![Accept bitcoin payments   Blockonomics(2)](https://user-images.githubusercontent.com/39666372/83053515-21516900-a051-11ea-837e-437bfd3c36bf.png)

- Also ensure you have added the api key and secret to the config.ini file?

Please let me know if this helps solve your issue with new address generation.
